# Generated by Django 5.2.7 on 2025-11-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_crypto_options_crypto_change_24h_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reciever',
            new_name='receiver',
        ),
        migrations.AddField(
            model_name='transaction',
            name='chain',
            field=models.CharField(default='BTC', max_length=10),
        ),
    ]
