# Generated by Django 5.2.7 on 2025-11-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_reciever_transaction_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='market_cap',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
    ]
