# Generated by Django 5.2.7 on 2025-12-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_crypto_market_cap_alter_crypto_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_anomaly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
    ]
